### ISSUE TITLE
Gnome 42 is being phased out.

### ISSUE THREAD

**Issue by Arup65** [flathub/com.github.fushinari.Wordbook#4]
Please update to latest gnome dependencies.

Thanks

![image](https://user-images.githubusercontent.com/5519251/227766070-12779301-0861-4e25-a376-52c0501372ff.png)

**Comment by mufeedali** [comment]
Thanks for letting me know. I will be updating it soon.

**Comment by mufeedali** [comment]
Should now be updated.

**Comment by Arup65** [comment]
Thank you, great program btw.

**Comment by mufeedali** [comment]
Thanks! :) I plan to update the app soon
